import turtle
screen = turtle.Screen()
screen.bgcolor('orange')
pen = turtle.Turtle()
pen.shape('turtle')
pen.speed(1)
pen.fillcolor('blue')
pen.begin_fill()
pen.circle(80)
pen.end_fill()
turtle.done()